[package]
name = "pongxelflut"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bufstream = "0.1.4"
glam = { version = "0.29.2", features = ["fast-math"] }
input = "0.9.1"
libc = "0.2.169"
net2 = "0.2.39"
random = "0.14.0"
regex = "1.11.1"
